/**
 * Express type augmentation.
 *
 * `authenticate` attaches the signed-in user to the request, so every handler
 * downstream of it can read `req.user` without casting.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { User } from '@prisma/client'

declare global {
  namespace Express {
    interface Request {
      user?: User
    }
  }
}

export {}
