/**
 * Auth request handlers.
 *
 * Express 5 forwards rejected promises to the error handler, so these are
 * plain async functions with no try/catch and no wrapper.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { Request, Response } from 'express'
import { requireUser } from '../../middleware/authenticate.js'
import * as authService from './auth.service.js'

export async function login(req: Request, res: Response): Promise<void> {
  res.json(await authService.login(req.body))
}

export async function register(req: Request, res: Response): Promise<void> {
  res.status(201).json(await authService.register(req.body))
}

export async function me(req: Request, res: Response): Promise<void> {
  res.json(authService.serializeUser(requireUser(req)))
}

export async function updateMe(req: Request, res: Response): Promise<void> {
  res.json(await authService.updateProfile(requireUser(req), req.body))
}

export async function changePassword(req: Request, res: Response): Promise<void> {
  await authService.changePassword(requireUser(req), req.body)
  res.json({ detail: 'Password changed successfully.' })
}

export async function forgotPassword(_req: Request, res: Response): Promise<void> {
  // TODO: Implement email sending logic.
  // Always reports success so the endpoint cannot be used to discover which
  // email addresses have accounts.
  res.json({ detail: 'If an account exists, a reset email has been sent.' })
}

export async function resetPassword(_req: Request, res: Response): Promise<void> {
  // TODO: Implement token verification and password reset.
  res.json({ detail: 'Password has been reset successfully.' })
}

export async function logout(_req: Request, res: Response): Promise<void> {
  // Tokens are stateless. Add a revocation list here if you need refresh
  // tokens to stop working the moment a user signs out.
  res.json({ detail: 'Successfully logged out.' })
}

export async function refresh(req: Request, res: Response): Promise<void> {
  res.json(authService.refreshTokens(req.body.refresh))
}
