/**
 * Auth business logic.
 *
 * Kept out of the controllers so it can be tested directly and reused from
 * scripts or background jobs.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { User } from '@prisma/client'
import { prisma } from '../../db/client.js'
import { ApiError } from '../../utils/errors.js'
import { DUMMY_PASSWORD_HASH, hashPassword, verifyPassword } from '../../utils/password.js'
import { issueTokens, verifyToken, type TokenPair } from '../../utils/tokens.js'
import type {
  ChangePasswordInput,
  LoginInput,
  PatchedUserInput,
  RegisterInput,
  UserOutput,
} from './auth.schemas.js'

/** Public shape of a user — never includes the password hash. */
export function serializeUser(user: User): UserOutput {
  return {
    id: user.id,
    email: user.email,
    first_name: user.first_name,
    last_name: user.last_name,
    date_joined: user.date_joined.toISOString(),
  }
}

export async function login({ email, password }: LoginInput): Promise<TokenPair> {
  const user = await prisma.user.findUnique({ where: { email } })

  // Verify against a real hash either way, so a missing account and a wrong
  // password take the same time and cannot be told apart by timing.
  const valid = await verifyPassword(password, user?.password ?? DUMMY_PASSWORD_HASH)

  if (!user || !valid) {
    throw ApiError.nonField('Invalid email or password.')
  }
  if (!user.is_active) {
    throw ApiError.nonField('User account is disabled.')
  }

  return issueTokens(user.id)
}

export async function register(input: RegisterInput): Promise<TokenPair> {
  const existing = await prisma.user.findUnique({ where: { email: input.email } })
  if (existing) {
    throw ApiError.validation({
      email: ['A user with this email address already exists.'],
    })
  }

  const user = await prisma.user.create({
    data: {
      email: input.email,
      first_name: input.first_name,
      last_name: input.last_name,
      password: await hashPassword(input.password),
    },
  })

  return issueTokens(user.id)
}

export async function updateProfile(
  user: User,
  input: PatchedUserInput
): Promise<UserOutput> {
  const updated = await prisma.user.update({
    where: { id: user.id },
    data: input,
  })
  return serializeUser(updated)
}

export async function changePassword(
  user: User,
  input: ChangePasswordInput
): Promise<void> {
  const valid = await verifyPassword(input.old_password, user.password)
  if (!valid) {
    throw ApiError.validation({
      old_password: ['Current password is incorrect.'],
    })
  }

  await prisma.user.update({
    where: { id: user.id },
    data: { password: await hashPassword(input.new_password) },
  })
}

/**
 * Exchange a refresh token for a new pair.
 *
 * Both tokens are reissued, matching SimpleJWT's ROTATE_REFRESH_TOKENS on the
 * Django backend. Unlike Django it does NOT blacklist the old refresh token —
 * these tokens are stateless, so the previous one stays valid until it
 * expires. To close that window, persist issued refresh tokens and reject any
 * that have been rotated or logged out.
 */
export function refreshTokens(refresh: string): TokenPair {
  const { user_id } = verifyToken(refresh, 'refresh')
  return issueTokens(user_id)
}
