/**
 * Auth request and response schemas.
 *
 * These are the Zod equivalents of the DRF serializers in the Django backend,
 * field for field — the React auth adapter posts the same bodies to either one.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { z } from '../../config/zod.js'

/** Mirrors Django's `AUTH_PASSWORD_VALIDATORS` minimum length. */
const password = z.string().min(8, 'This password is too short. It must contain at least 8 characters.')

export const UserSchema = z
  .object({
    id: z.number().int(),
    email: z.string().email('Enter a valid email address.'),
    first_name: z.string(),
    last_name: z.string(),
    date_joined: z.string().datetime(),
  })
  .openapi('User')

export const TokenSchema = z
  .object({
    access: z.string(),
    refresh: z.string(),
  })
  .openapi('Token')

export const DetailSchema = z
  .object({
    detail: z.string(),
  })
  .openapi('Detail')

export const LoginSchema = z
  .object({
    email: z.string().email('Enter a valid email address.'),
    password: z.string().min(1, 'This field may not be blank.'),
  })
  .openapi('Login')

export const RegisterSchema = z
  .object({
    email: z.string().email('Enter a valid email address.'),
    first_name: z.string().min(1, 'This field may not be blank.'),
    last_name: z.string().default(''),
    password,
    password_confirm: z.string(),
  })
  .refine((data) => data.password === data.password_confirm, {
    message: 'Passwords do not match.',
    path: ['password_confirm'],
  })
  .openapi('Register')

export const PatchedUserSchema = z
  .object({
    first_name: z.string().min(1, 'This field may not be blank.').optional(),
    last_name: z.string().optional(),
  })
  .openapi('PatchedUser')

export const ChangePasswordSchema = z
  .object({
    old_password: z.string().min(1, 'This field may not be blank.'),
    new_password: password,
  })
  .openapi('ChangePassword')

export const ForgotPasswordSchema = z
  .object({
    email: z.string().email('Enter a valid email address.'),
  })
  .openapi('ForgotPassword')

export const ResetPasswordSchema = z
  .object({
    token: z.string().min(1, 'This field may not be blank.'),
    password,
    password_confirm: z.string(),
  })
  .refine((data) => data.password === data.password_confirm, {
    message: 'Passwords do not match.',
    path: ['password_confirm'],
  })
  .openapi('ResetPassword')

export const RefreshSchema = z
  .object({
    refresh: z.string().min(1, 'This field may not be blank.'),
  })
  .openapi('Refresh')

export const LogoutSchema = z
  .object({
    refresh: z.string().optional(),
  })
  .openapi('Logout')

export type LoginInput = z.infer<typeof LoginSchema>
export type RegisterInput = z.infer<typeof RegisterSchema>
export type PatchedUserInput = z.infer<typeof PatchedUserSchema>
export type ChangePasswordInput = z.infer<typeof ChangePasswordSchema>
export type ResetPasswordInput = z.infer<typeof ResetPasswordSchema>
export type UserOutput = z.infer<typeof UserSchema>
