/**
 * Auth routes.
 *
 * Each endpoint is declared twice on purpose: once on the Express router, and
 * once in the OpenAPI registry. The registry entry is what `npm run openapi`
 * exports and `blacksmith sync` turns into the typed frontend client, so the
 * two must stay in step.
 *
 * `operationId` values match what drf-spectacular emits for the Django
 * backend, which is what keeps the generated hook names identical across both.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { Router } from 'express'
import { bearerAuth, jsonContent, registry } from '../../config/openapi.js'
import { authenticate } from '../../middleware/authenticate.js'
import { validateBody } from '../../middleware/validate.js'
import * as controller from './auth.controller.js'
import {
  ChangePasswordSchema,
  DetailSchema,
  ForgotPasswordSchema,
  LoginSchema,
  LogoutSchema,
  PatchedUserSchema,
  RefreshSchema,
  RegisterSchema,
  ResetPasswordSchema,
  TokenSchema,
  UserSchema,
} from './auth.schemas.js'

const TAGS = ['auth']
const SECURED = [{ [bearerAuth.name]: [] }]

export const authRouter = Router()

// ── POST /api/auth/login/ ──────────────────────────────────────────────
registry.registerPath({
  method: 'post',
  path: '/api/auth/login/',
  operationId: 'auth_login_create',
  tags: TAGS,
  description:
    'Authenticate with email and password. Returns JWT access and refresh tokens.',
  request: { body: jsonContent(LoginSchema) },
  responses: {
    200: { description: 'Authenticated.', ...jsonContent(TokenSchema) },
  },
})
authRouter.post('/login/', validateBody(LoginSchema), controller.login)

// ── POST /api/auth/register/ ───────────────────────────────────────────
registry.registerPath({
  method: 'post',
  path: '/api/auth/register/',
  operationId: 'auth_register_create',
  tags: TAGS,
  description: 'Create a new user account. Returns JWT tokens.',
  request: { body: jsonContent(RegisterSchema) },
  responses: {
    201: { description: 'Account created.', ...jsonContent(TokenSchema) },
  },
})
authRouter.post('/register/', validateBody(RegisterSchema), controller.register)

// ── GET /api/auth/me/ ──────────────────────────────────────────────────
registry.registerPath({
  method: 'get',
  path: '/api/auth/me/',
  operationId: 'auth_me_retrieve',
  tags: TAGS,
  security: SECURED,
  description: 'Get the current authenticated user profile.',
  responses: {
    200: { description: 'The current user.', ...jsonContent(UserSchema) },
  },
})
authRouter.get('/me/', authenticate, controller.me)

// ── PATCH /api/auth/me/ ────────────────────────────────────────────────
registry.registerPath({
  method: 'patch',
  path: '/api/auth/me/',
  operationId: 'auth_me_partial_update',
  tags: TAGS,
  security: SECURED,
  description: 'Update the current authenticated user profile.',
  request: { body: jsonContent(PatchedUserSchema) },
  responses: {
    200: { description: 'The updated user.', ...jsonContent(UserSchema) },
  },
})
authRouter.patch('/me/', authenticate, validateBody(PatchedUserSchema), controller.updateMe)

// ── POST /api/auth/change-password/ ────────────────────────────────────
registry.registerPath({
  method: 'post',
  path: '/api/auth/change-password/',
  operationId: 'auth_change_password_create',
  tags: TAGS,
  security: SECURED,
  description: 'Change the current user password.',
  request: { body: jsonContent(ChangePasswordSchema) },
  responses: {
    200: { description: 'Password changed.', ...jsonContent(DetailSchema) },
  },
})
authRouter.post(
  '/change-password/',
  authenticate,
  validateBody(ChangePasswordSchema),
  controller.changePassword
)

// ── POST /api/auth/forgot-password/ ────────────────────────────────────
registry.registerPath({
  method: 'post',
  path: '/api/auth/forgot-password/',
  operationId: 'auth_forgot_password_create',
  tags: TAGS,
  description: 'Request a password reset email.',
  request: { body: jsonContent(ForgotPasswordSchema) },
  responses: {
    200: { description: 'Reset email queued.', ...jsonContent(DetailSchema) },
  },
})
authRouter.post(
  '/forgot-password/',
  validateBody(ForgotPasswordSchema),
  controller.forgotPassword
)

// ── POST /api/auth/reset-password/ ─────────────────────────────────────
registry.registerPath({
  method: 'post',
  path: '/api/auth/reset-password/',
  operationId: 'auth_reset_password_create',
  tags: TAGS,
  description: 'Reset password using a token from the reset email.',
  request: { body: jsonContent(ResetPasswordSchema) },
  responses: {
    200: { description: 'Password reset.', ...jsonContent(DetailSchema) },
  },
})
authRouter.post(
  '/reset-password/',
  validateBody(ResetPasswordSchema),
  controller.resetPassword
)

// ── POST /api/auth/logout/ ─────────────────────────────────────────────
registry.registerPath({
  method: 'post',
  path: '/api/auth/logout/',
  operationId: 'auth_logout_create',
  tags: TAGS,
  security: SECURED,
  description: 'Log the current user out.',
  request: { body: jsonContent(LogoutSchema) },
  responses: {
    200: { description: 'Logged out.', ...jsonContent(DetailSchema) },
  },
})
authRouter.post('/logout/', authenticate, validateBody(LogoutSchema), controller.logout)

// ── POST /api/auth/refresh/ ────────────────────────────────────────────
registry.registerPath({
  method: 'post',
  path: '/api/auth/refresh/',
  operationId: 'auth_refresh_create',
  tags: TAGS,
  description: 'Exchange a valid refresh token for a new token pair.',
  request: { body: jsonContent(RefreshSchema) },
  responses: {
    200: { description: 'New token pair.', ...jsonContent(TokenSchema) },
  },
})
authRouter.post('/refresh/', validateBody(RefreshSchema), controller.refresh)
