/**
 * Where the test suite's database lives.
 *
 * Read by vitest.config.ts (for the worker environment) and by global-setup
 * (which pushes the schema). Both must agree, or the schema lands in one
 * database while the tests query another.
 *
 * SQLite paths are resolved relative to prisma/schema.prisma, so this is
 * prisma/test.db — separate from the dev database, and git-ignored.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

export const TEST_DATABASE_URL = 'file:./test.db'
