/**
 * Creates the test database once per run.
 *
 * The SQLite file is deleted and rebuilt from the current schema, so a run
 * never depends on leftover state or on prisma/migrations being up to date.
 *
 * Only the file named by DATABASE_URL is removed, and only when it is a local
 * SQLite file — this must never be able to reset a real database.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { TEST_DATABASE_URL } from './database-url.js'

// vitest.config.ts puts this in the workers' environment; globalSetup runs in
// the main process, so it is read from there and passed to Prisma explicitly.
// Both come from TEST_DATABASE_URL so the schema push and the tests can never
// target different databases.
const DATABASE_URL = process.env.DATABASE_URL ?? TEST_DATABASE_URL

/** Absolute path of a `file:` SQLite URL, or null for any other database. */
function sqliteFile(url: string): string | null {
  if (!url.startsWith('file:')) return null
  // Prisma resolves relative SQLite paths against the schema's directory.
  return path.resolve('prisma', url.slice('file:'.length))
}

export default function setup(): void {
  const dbFile = sqliteFile(DATABASE_URL)
  if (dbFile) {
    fs.rmSync(dbFile, { force: true })
    fs.rmSync(`${dbFile}-journal`, { force: true })
  }

  execFileSync('npx', ['prisma', 'db', 'push', '--skip-generate'], {
    stdio: 'inherit',
    env: { ...process.env, DATABASE_URL },
  })
}
