/**
 * Per-file test setup.
 *
 * Empties every table after each test so cases stay independent. Reading the
 * table list from SQLite means resources added by `blacksmith make:resource`
 * are cleaned up without touching this file.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { afterAll, afterEach } from 'vitest'
import { prisma } from '../db/client.js'

async function tableNames(): Promise<string[]> {
  const rows = await prisma.$queryRawUnsafe<{ name: string }[]>(
    "SELECT name FROM sqlite_master WHERE type = 'table' " +
      "AND name NOT LIKE '_prisma%' AND name NOT LIKE 'sqlite_%'"
  )
  // `users` is the target of every resource foreign key, so it goes last.
  return rows
    .map((row) => row.name)
    .sort((a, b) => Number(a === 'users') - Number(b === 'users'))
}

afterEach(async () => {
  for (const name of await tableNames()) {
    await prisma.$executeRawUnsafe(`DELETE FROM "${name}"`)
  }
})

afterAll(async () => {
  await prisma.$disconnect()
})
