/**
 * Shared test helpers.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import request from 'supertest'
import { createApp } from '../app.js'
import { prisma } from '../db/client.js'
import { hashPassword } from '../utils/password.js'
import { issueTokens } from '../utils/tokens.js'

export const app = createApp()
export const api = () => request(app)

export const TEST_PASSWORD = 'sup3r-secret-pw'

export async function createUser(overrides: Partial<{
  email: string
  first_name: string
  last_name: string
  password: string
  is_active: boolean
}> = {}) {
  const { password = TEST_PASSWORD, ...rest } = overrides

  return prisma.user.create({
    data: {
      email: 'test@example.com',
      first_name: 'Test',
      last_name: 'User',
      ...rest,
      password: await hashPassword(password),
    },
  })
}

/** An `Authorization` header for a freshly created user. */
export async function authHeader(userId: number): Promise<[string, string]> {
  const { access } = issueTokens(userId)
  return ['Authorization', `Bearer ${access}`]
}
