/**
 * Prisma client singleton.
 *
 * Re-used across hot reloads in development so `tsx watch` does not exhaust the
 * connection pool by creating a new client on every restart.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { PrismaClient } from '@prisma/client'
import { isProduction } from '../config/env.js'

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient }

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: isProduction ? ['error'] : ['error', 'warn'],
  })

if (!isProduction) {
  globalForPrisma.prisma = prisma
}
