/**
 * Express application.
 *
 * Exported without calling `listen` so tests can drive it with supertest.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import express from 'express'
import cors from 'cors'
import swaggerUi from 'swagger-ui-express'
import { corsOrigins, isProduction } from './config/env.js'
import { buildOpenApiDocument } from './config/openapi.js'
import { errorHandler, notFoundHandler } from './middleware/error-handler.js'
import { apiRouter } from './modules/index.js'

export function createApp() {
  const app = express()

  // Pagination links are absolute, built from req.protocol and the Host
  // header. Behind a TLS terminator (nginx, a load balancer, most PaaS) those
  // read as plain http and the internal host unless X-Forwarded-* is trusted.
  if (isProduction) {
    app.set('trust proxy', 1)
  }

  app.use(
    cors({
      // Development mirrors Django's CORS_ALLOW_ALL_ORIGINS
      origin: isProduction ? corsOrigins : true,
      credentials: true,
    })
  )
  app.use(express.json())
  app.use(express.urlencoded({ extended: true }))

  // OpenAPI schema and documentation, at the same paths Django serves them
  const openApiDocument = buildOpenApiDocument()
  app.get('/api/schema/', (_req, res) => {
    res.json(openApiDocument)
  })
  app.use('/api/docs/', swaggerUi.serve, swaggerUi.setup(openApiDocument))

  app.use('/api', apiRouter)

  app.use(notFoundHandler)
  app.use(errorHandler)

  return app
}
