/**
 * Server entry point.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { createApp } from './app.js'
import { env } from './config/env.js'

const app = createApp()

app.listen(env.PORT, () => {
  console.log(`Clinic appointment booking API   → http://localhost:${env.PORT}`)
  console.log(`Swagger              → http://localhost:${env.PORT}/api/docs/`)
  console.log(`OpenAPI schema       → http://localhost:${env.PORT}/api/schema/`)
})
