/**
 * Offline OpenAPI export.
 *
 *   npm run openapi              → writes ./openapi.json
 *   npm run openapi -- <path>    → writes <path>
 *
 * This is the equivalent of Django's `manage.py spectacular --file`: it builds
 * the document without starting a server or touching the database, which is
 * what lets `blacksmith sync` and CI generate the frontend client offline.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import fs from 'node:fs'
import path from 'node:path'
import { buildOpenApiDocument } from './config/openapi.js'
// Importing the router registers every route's schemas on the registry.
import './modules/index.js'

const outPath = path.resolve(process.argv[2] ?? 'openapi.json')

fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, `${JSON.stringify(buildOpenApiDocument(), null, 2)}\n`, 'utf-8')

console.log(`OpenAPI schema written to ${outPath}`)
