/**
 * API router.
 *
 * Mounted at `/api`. Resource routers are registered here by
 * `blacksmith make:resource` — keep the marker comments in place.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { Router } from 'express'
import { authRouter } from './auth/auth.routes.js'
// blacksmith:import

export const apiRouter = Router()

apiRouter.use('/auth', authRouter)
// blacksmith:routes
