/**
 * API errors, in the shapes Django REST Framework returns.
 *
 * The React client parses these in `src/shared/hooks/api-error.ts`, so the
 * body shapes here are a contract, not a style choice:
 *   { "detail": "..." }
 *   { "non_field_errors": ["..."] }
 *   { "field_name": ["..."] }
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

export type ErrorBody = Record<string, unknown>

export class ApiError extends Error {
  readonly status: number
  readonly body: ErrorBody

  constructor(status: number, body: ErrorBody) {
    super(typeof body.detail === 'string' ? body.detail : 'API error')
    this.name = 'ApiError'
    this.status = status
    this.body = body
  }

  /** `{ "detail": "..." }` — the shape DRF uses for most errors. */
  static detail(status: number, detail: string): ApiError {
    return new ApiError(status, { detail })
  }

  /** `{ "field": ["msg"] }` — per-field validation errors. */
  static validation(fieldErrors: Record<string, string[]>): ApiError {
    return new ApiError(400, fieldErrors)
  }

  /** `{ "non_field_errors": ["msg"] }` — validation not tied to one field. */
  static nonField(...messages: string[]): ApiError {
    return new ApiError(400, { non_field_errors: messages })
  }

  static badRequest(detail: string): ApiError {
    return ApiError.detail(400, detail)
  }

  static unauthorized(
    detail = 'Authentication credentials were not provided.'
  ): ApiError {
    return ApiError.detail(401, detail)
  }

  static forbidden(
    detail = 'You do not have permission to perform this action.'
  ): ApiError {
    return ApiError.detail(403, detail)
  }

  static notFound(detail = 'Not found.'): ApiError {
    return ApiError.detail(404, detail)
  }
}
