/**
 * Page-number pagination matching DRF's `PageNumberPagination`.
 *
 * The generated React hooks read `count` / `next` / `previous` / `results`
 * straight off the response, so the envelope shape and the absolute page URLs
 * both have to match what DRF produces.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { Request } from 'express'

export const PAGE_SIZE = 20

export interface Page<T> {
  count: number
  next: string | null
  previous: string | null
  results: T[]
}

/** Absolute URL of the current request with `page` set to `page`. */
function pageUrl(req: Request, page: number): string {
  const url = new URL(
    req.originalUrl,
    `${req.protocol}://${req.get('host') ?? 'localhost'}`
  )
  // DRF omits `page=1` — the first page is the bare collection URL.
  if (page === 1) {
    url.searchParams.delete('page')
  } else {
    url.searchParams.set('page', String(page))
  }
  return url.toString()
}

/** Clamp an incoming `page` query param to a usable page number. */
export function resolvePage(value: unknown): number {
  const page = Number(value)
  return Number.isInteger(page) && page > 0 ? page : 1
}

/** Prisma `skip`/`take` for a page number. */
export function pageBounds(page: number, pageSize = PAGE_SIZE) {
  return { skip: (page - 1) * pageSize, take: pageSize }
}

export function paginated<T>(
  req: Request,
  results: T[],
  count: number,
  page: number,
  pageSize = PAGE_SIZE
): Page<T> {
  const totalPages = Math.max(1, Math.ceil(count / pageSize))

  return {
    count,
    next: page < totalPages ? pageUrl(req, page + 1) : null,
    previous: page > 1 ? pageUrl(req, page - 1) : null,
    results,
  }
}
