/**
 * Password hashing.
 *
 * bcryptjs is pure JavaScript, so a generated project installs and runs with
 * no native toolchain.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { randomBytes } from 'node:crypto'
import bcrypt from 'bcryptjs'
import { isTest } from '../config/env.js'

// Hashing dominates test runtime, and test passwords do not need to be
// expensive — the same trade-off the Django template makes with MD5 hashing.
const ROUNDS = isTest ? 4 : 10

/**
 * A hash of a random value that no password can match, used to spend the same
 * work verifying a missing account as a real one.
 *
 * Computed once at startup rather than per request: hashing on each call would
 * make the unauthenticated path cost about twice the authenticated one, which
 * is a lever an attacker can pull with nothing but a list of guessed emails.
 * Generated rather than hardcoded so it is never a known digest and always
 * matches the configured cost factor.
 */
export const DUMMY_PASSWORD_HASH = bcrypt.hashSync(
  randomBytes(32).toString('hex'),
  ROUNDS
)

export function hashPassword(plain: string): Promise<string> {
  return bcrypt.hash(plain, ROUNDS)
}

export function verifyPassword(plain: string, hashed: string): Promise<boolean> {
  return bcrypt.compare(plain, hashed)
}
