/**
 * JWT access and refresh tokens.
 *
 * Mirrors what SimpleJWT issues on the Django backend: a short-lived access
 * token and a longer-lived refresh token, both carrying the user id, and
 * distinguished by a `token_type` claim.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import jwt from 'jsonwebtoken'
import { env } from '../config/env.js'
import { ApiError } from './errors.js'

export type TokenType = 'access' | 'refresh'

export interface TokenPayload {
  user_id: number
  token_type: TokenType
}

export interface TokenPair {
  access: string
  refresh: string
}

function sign(userId: number, type: TokenType, expiresInSeconds: number): string {
  const payload: TokenPayload = { user_id: userId, token_type: type }
  return jwt.sign(payload, env.JWT_SECRET, { expiresIn: expiresInSeconds })
}

export function issueTokens(userId: number): TokenPair {
  return {
    access: sign(userId, 'access', env.ACCESS_TOKEN_LIFETIME_MINUTES * 60),
    refresh: sign(userId, 'refresh', env.REFRESH_TOKEN_LIFETIME_DAYS * 86400),
  }
}

/**
 * Verify a token and assert its type.
 *
 * Throws a 401 with SimpleJWT's wording, which is what the React client's
 * refresh interceptor expects to see.
 */
export function verifyToken(token: string, expected: TokenType): TokenPayload {
  let payload: TokenPayload
  try {
    payload = jwt.verify(token, env.JWT_SECRET) as TokenPayload
  } catch {
    throw ApiError.unauthorized('Given token not valid for any token type.')
  }

  if (payload.token_type !== expected) {
    throw ApiError.unauthorized('Given token not valid for any token type.')
  }

  return payload
}
