/**
 * Environment configuration.
 *
 * Parsed and validated once at startup so a missing or malformed variable
 * fails loudly here instead of somewhere deep in a request.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import 'dotenv/config'
import { z } from './zod.js'

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.coerce.number().int().positive().default(8000),
  DATABASE_URL: z.string().min(1).default('file:./dev.db'),
  JWT_SECRET: z.string().min(1).default('change-me-in-production'),
  ACCESS_TOKEN_LIFETIME_MINUTES: z.coerce.number().int().positive().default(30),
  REFRESH_TOKEN_LIFETIME_DAYS: z.coerce.number().int().positive().default(7),
  CORS_ALLOWED_ORIGINS: z
    .string()
    .default('http://localhost:5173,http://localhost:3000'),
})

export const env = envSchema.parse(process.env)

export const isProduction = env.NODE_ENV === 'production'
export const isTest = env.NODE_ENV === 'test'

/** CORS origins as a list. In development every origin is allowed. */
export const corsOrigins = env.CORS_ALLOWED_ORIGINS.split(',')
  .map((origin) => origin.trim())
  .filter(Boolean)
