/**
 * OpenAPI registry and document builder.
 *
 * Every route registers its request and response schemas here, which is what
 * lets `npm run openapi` emit a complete document without booting the server —
 * the offline schema export that `blacksmith sync` consumes.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import {
  OpenAPIRegistry,
  OpenApiGeneratorV31,
} from '@asteasolutions/zod-to-openapi'
import type { ZodTypeAny } from 'zod'
import { env } from './env.js'

export const registry = new OpenAPIRegistry()

/** Bearer JWT, mirroring the `jwtAuth` scheme the Django backend advertises. */
export const bearerAuth = registry.registerComponent(
  'securitySchemes',
  'jwtAuth',
  {
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT',
  }
)

/**
 * `content: { 'application/json': { schema } }`, which every request body and
 * response in the registry needs.
 */
export function jsonContent(schema: ZodTypeAny) {
  return {
    content: {
      'application/json': { schema },
    },
  }
}

export function buildOpenApiDocument() {
  const generator = new OpenApiGeneratorV31(registry.definitions)

  return generator.generateDocument({
    openapi: '3.1.0',
    info: {
      title: 'Clinic appointment booking API',
      version: '1.0.0',
      description:
        'API documentation for Clinic appointment booking. Generated by Blacksmith.',
    },
    servers: [{ url: `http://localhost:${env.PORT}` }],
  })
}
