/**
 * Zod, extended with OpenAPI metadata support.
 *
 * `extendZodWithOpenApi` must run before any schema calls `.openapi()`, so
 * every module imports `z` from here rather than from `zod` directly.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import { z } from 'zod'
import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi'

extendZodWithOpenApi(z)

export { z }
