/**
 * JWT authentication middleware.
 *
 * Equivalent to DRF's `IsAuthenticated` + `JWTAuthentication` pair: reads a
 * `Bearer` token, loads the user, and rejects with DRF's own wording so the
 * React client's 401 refresh interceptor behaves identically.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { NextFunction, Request, Response } from 'express'
import { prisma } from '../db/client.js'
import { ApiError } from '../utils/errors.js'
import { verifyToken } from '../utils/tokens.js'

export async function authenticate(
  req: Request,
  _res: Response,
  next: NextFunction
): Promise<void> {
  const header = req.headers.authorization

  if (!header?.startsWith('Bearer ')) {
    throw ApiError.unauthorized()
  }

  const { user_id } = verifyToken(header.slice('Bearer '.length).trim(), 'access')
  const user = await prisma.user.findUnique({ where: { id: user_id } })

  if (!user || !user.is_active) {
    throw ApiError.unauthorized('User not found or inactive.')
  }

  req.user = user
  next()
}

/** Narrow `req.user` for handlers mounted behind `authenticate`. */
export function requireUser(req: Request) {
  if (!req.user) {
    throw ApiError.unauthorized()
  }
  return req.user
}
