/**
 * Error handling.
 *
 * Every error leaves the API in a shape `parseApiError` on the frontend
 * understands. Express 5 forwards rejected promises here automatically, so
 * handlers can be plain `async` functions with no wrapper.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { NextFunction, Request, Response } from 'express'
import { ZodError } from 'zod'
import { Prisma } from '@prisma/client'
import { ApiError } from '../utils/errors.js'
import { isProduction } from '../config/env.js'
import { toFieldErrors } from './validate.js'

/** Unmatched route — DRF's 404 body. */
export function notFoundHandler(_req: Request, res: Response): void {
  res.status(404).json({ detail: 'Not found.' })
}

export function errorHandler(
  error: unknown,
  _req: Request,
  res: Response,
  next: NextFunction
): void {
  if (res.headersSent) {
    next(error)
    return
  }

  if (error instanceof ApiError) {
    res.status(error.status).json(error.body)
    return
  }

  // A schema validated outside `validateBody` (a service-level check, say)
  if (error instanceof ZodError) {
    res.status(400).json(toFieldErrors(error))
    return
  }

  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    // P2025: record required by the operation was not found
    if (error.code === 'P2025') {
      res.status(404).json({ detail: 'Not found.' })
      return
    }
    // P2002: unique constraint violation
    if (error.code === 'P2002') {
      const target = error.meta?.target
      const fields = Array.isArray(target) ? target : ['non_field_errors']
      res.status(400).json(
        Object.fromEntries(
          fields.map((field) => [String(field), ['This field must be unique.']])
        )
      )
      return
    }
  }

  if (!isProduction) {
    console.error(error)
  }

  res.status(500).json({ detail: 'A server error occurred.' })
}
