/**
 * Request validation middleware.
 *
 * A Zod failure becomes DRF's per-field error body — `{ "email": ["..."] }` —
 * which is what the React client renders next to the offending form field.
 *
 * Generated by Blacksmith. You own this file — customize as needed.
 */

import type { NextFunction, Request, RequestHandler, Response } from 'express'
import type { ZodError, ZodTypeAny, z } from 'zod'
import { ApiError } from '../utils/errors.js'

/** Group Zod issues by field, the way a DRF serializer reports them. */
export function toFieldErrors(error: ZodError): Record<string, string[]> {
  const fieldErrors: Record<string, string[]> = {}

  for (const issue of error.issues) {
    const key = issue.path.length > 0 ? issue.path.join('.') : 'non_field_errors'
    ;(fieldErrors[key] ??= []).push(issue.message)
  }

  return fieldErrors
}

function parseOrThrow<T extends ZodTypeAny>(schema: T, value: unknown): z.infer<T> {
  const result = schema.safeParse(value)
  if (!result.success) {
    throw ApiError.validation(toFieldErrors(result.error))
  }
  return result.data
}

export function validateBody<T extends ZodTypeAny>(schema: T): RequestHandler {
  return (req: Request, _res: Response, next: NextFunction) => {
    req.body = parseOrThrow(schema, req.body)
    next()
  }
}

/**
 * Validate query params.
 *
 * Express 5 makes `req.query` a getter, so the parsed result is stashed on
 * `res.locals.query` instead of being assigned back.
 */
export function validateQuery<T extends ZodTypeAny>(schema: T): RequestHandler {
  return (req: Request, res: Response, next: NextFunction) => {
    res.locals.query = parseOrThrow(schema, req.query)
    next()
  }
}

/** Read what `validateQuery` parsed, typed. */
export function validatedQuery<T>(res: Response): T {
  return res.locals.query as T
}
